# Generated by Django 6.0.3 on 2026-03-24 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(default='名古屋グルメ', max_length=100, verbose_name='サービス名')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='service/', verbose_name='ロゴ')),
                ('contact_email', models.EmailField(blank=True, max_length=254, verbose_name='お問い合わせメールアドレス')),
                ('terms', models.TextField(blank=True, verbose_name='利用規約')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': 'サービス設定',
            },
        ),
    ]
